%Terrain mapping

%This program will generate a temperature map frtom the data obtained from
%the Arduino program. It will also plot the coordinates of the data points,
%so that it can be judged whether or not ht edensity of the points is
%enough.
%The data is imported from the file generated by the arduino and stored in
%the SD card. Substitute the GPSLOG13.TXT for your own data sets (or leave
%this line as it is if you want to see an example of the program's
%functionality).
data= importdata('GPSLOG13.TXT');

%The data is splited between diferent arrays for posterior processing
x = data(:,1);
y = data(:,2);
v = data(:,3);


%the number of divisions is set for each direction
M=200;
N=200;

%A mesh is generated. The data points will be assigned to the nodes of this
%mesh. The limits of this mesh are the minimum value of x and y and the
%maximum value of x and y.
[xq,yq] = meshgrid(min(x):((max(x)-min(x))/N):max(x), min(y):((max(y)-min(y))/M):max(y));

vq = griddata(x,y,v,xq,yq,'linear');



%a figure with the results is generated and displayed. It will be shown
%from atop, but the map is actually 3D and can be rotated.
figure
surface=surf(xq,yq,vq);
set(surface,'edgecolor','none')
hold on
plot3(x,y,v,'x');

view(0, 90)
axis equal